### ISSUE TITLE
Missing element ReqdExctnDt

### ISSUE THREAD

**Issue by kopeclu2** [inisos/bank4j#1]
Hello i am using this library for creating SEPA XML. I used validatorhttps://www.mobilefish.com/services/sepa_xml_validation/sepa_xml_validation.php an there is missing required attribute ReqdExctnDt which is right. In all documentation files this attribute is required. I saw your code and there is no usage of setter fot attribute ReqdExctnDt.

Error: 
XML document is well-formed.
XML document does not validate against XSD schema. Following XML errors found:
-----------------------------------------------------------------
            </PmtTpInf>
            <Dbtr>

Error, see line 24: 
Element '{urn:iso:std:iso:20022:tech:xsd:pain.001.001.03}Dbtr': This element is not expected. Expected is ( {urn:iso:std:iso:20022:tech:xsd:pain.001.001.03}ReqdExctnDt ).
-----------------------------------------------------------------

If you are going to do it can you extends SimpleTransaction for more attributes  ? Same dates are missing

Can you solve it ? 
Thank you so much

**Comment by valh1996** [comment]
Hi @kopeclu2,
Have you found a solution or simply overridden everything?

If not, @pblanchardie, has the project been abandoned? Should PR or a fork be favored?

**Comment by pblanchardie** [comment]
Hi,
Sorry for the late answer @kopeclu2 I did not see your issue.
I'll check today and keep you updated.
@valh1996 not abandonned, it will be updated.

**Comment by valh1996** [comment]
Thank you very much for your reply!
I look forward to hearing from you then, because your lib is really great, it's the easiest of all the ones I've tried 🙏🏻!

I'd like to take this opportunity to request an additional feature please:
- Add address lines (not the structured ones) for the creditor

**Comment by pblanchardie** [comment]
There was a mistake: `CreditTransfer.executionDate` was used as `CreDtTm` (message creation date and time).

I just renamed it to `CreditTransfer.creationDateTime` and added the missing `CreditTransfer.requestedExecutionDate` as per your request.

XML now validates against XSD. I will publish a new release.

> can you extends SimpleTransaction for more attributes ? Same dates are missing

@kopeclu2 what are you missing at the transaction level? feel free to create another issue if you want additional fields

**Comment by valh1996** [comment]
Thanks @pblanchardie
Is the 2.0.0 release already available on maven central? I can't install it.

**Comment by pblanchardie** [comment]
Hi @valh1996 @kopeclu2 
1.2.0 is now available on maven central
https://central.sonatype.com/artifact/io.inisos.bank4j/bank4j

2.0.0 will be available soon, it is a refactoring with builders, breaking change
