### ISSUE TITLE
[Feature] Add Intermediary agents

### ISSUE THREAD

**Issue by valh1996** [inisos/bank4j#9]
Hi @pblanchardie,

For some of our payments, we need to specify intermediary banks. For example, we need to enter a name and an account number for the first intermediary bank and a name and a swift for the second.

```
Credit Transfer Transaction Information 
+Intermediary Agent 1Account
++ ....
```

Specifications (page 53):
[ig-credit-transfer-v2.0.2-en.pdf](https://github.com/inisos/bank4j/files/13213613/ig-credit-transfer-v2.0.2-en.pdf)

Can this be implemented in the library please?

**Comment by pblanchardie** [comment]
@valh1996 have a look at https://github.com/inisos/bank4j#readme is it sufficient? or do you also need SchmeNm and other fields?

**Comment by valh1996** [comment]
@pblanchardie Sorry for the late reply, but yes, that's enough for now!
Thank you 🙏🏻
